version: 2.1

# Circle CI doesn't offer a git-only way to share env. vars between jobs that use
# different executors. Instead, add a non-standard shared_env_vars config and
# use a YAML anchor.
shared_env_vars: &shared_env_vars
  JVM_OPTS: -Xmx3200m
  ORG_GRADLE_PROJECT_RELEASE_STORE_FILE: /home/circleci/code/release.keystore
  ORG_GRADLE_PROJECT_RELEASE_STORE_PASSWORD_FILE: /home/circleci/code/release.password
  ORG_GRADLE_PROJECT_RELEASE_KEY_PASSWORD_FILE: /home/circleci/code/release.password

executors:
  android_executor:
    machine:
      image: android:default
    resource_class: large
    environment:
      <<: *shared_env_vars

  build_executor:
    docker:
      - image: cimg/android:2025.08.1
    resource_class: large
    environment:
      <<: *shared_env_vars

commands:
  cache_gradle_dependencies:
    steps:
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "settings.gradle" }}-{{ checksum "dependencies.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "settings.gradle" }}-{{ checksum "dependencies.gradle" }}

jobs:
  build:
    working_directory: ~/code
    executor: build_executor
    steps:
      - checkout
      - cache_gradle_dependencies
      - run:
          name: Create google-services.json (develop flavour)
          command: |
            rm app/src/develop/google-services.json # symlink, for local builds
            printf "%s" "${GOOGLE_SERVICES_DEVELOP}" | base64 --decode > app/src/develop/google-services.json
      - run:
          name: Create google-services.json (product flavour)
          command: |
            rm app/src/product/google-services.json # symlink, for local builds
            printf "%s" "${GOOGLE_SERVICES}" | base64 --decode > app/src/product/google-services.json
      - run:
          name: Create release.password
          command: printf "%s\n" "${RELEASE_KEY_PASSWORD:-}" > "${ORG_GRADLE_PROJECT_RELEASE_KEY_PASSWORD_FILE}"
      - run:
          name: Create release.keystore
          command: printf "%s" "${RELEASE_KEYSTORE:-}" | base64 --decode > "${ORG_GRADLE_PROJECT_RELEASE_STORE_FILE}"
      - run:
          name: gradle check
          command: ./gradlew check
      - run:
          name: gradle assembleProduct
          command: ./gradlew assembleProduct
      - run:
          name: gradle bundleProductRelease
          command: ./gradlew bundleProductRelease
      - run:
          name: gradle assembleProductDebugAndroidTest
          command: ./gradlew assembleProductDebugAndroidTest
      - store_artifacts: # https://circleci.com/docs/2.0/artifacts/
          path: app/build/outputs/apk/product/release/app-product-release.apk
          destination: apks/app-product-release.apk
      - store_artifacts:
          path: app/build/outputs/bundle/productRelease/app-product-release.aab
          destination: aabs/app-product-release.aab
      - store_artifacts:
          path: app/build/reports
          destination: reports/app
      - store_artifacts:
          path: build/reports
          destination: reports/project
      - store_test_results: # https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results
      - persist_to_workspace:
          root: .
          paths:
            - app/src/develop/google-services.json
            - app/src/product/google-services.json
            - build
            - app/build
  androidTest:
    parameters:
      system_image:
        type: string
    working_directory: ~/code
    executor: android_executor
    environment:
      SYSTEM_IMAGE: system-images;<< parameters.system_image >>
    steps:
      - checkout
      - attach_workspace:
          at: .
      - cache_gradle_dependencies
      - run:
          name: remove old reports
          command: rm -fR build/reports app/build/reports
      - run:
          name: Create avd
          command: |
            sdkmanager "${SYSTEM_IMAGE}"
            echo "no" | avdmanager --verbose create avd -n test -k "${SYSTEM_IMAGE}"
      - run:
          name: Launch emulator
          command: |
            emulator -avd test -delay-adb -verbose -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          background: true
      - run:
          name: Wait for emulator to start
          command: bin/waitForAndroidDeviceBoot
      - run:
          name: Disable emulator animations
          command: |
            adb shell settings put global window_animation_scale 0.0
            adb shell settings put global transition_animation_scale 0.0
            adb shell settings put global animator_duration_scale 0.0
      - run:
          name: androidTest
          command: ./gradlew connectedProductDebugAndroidTest --scan
      - store_artifacts:
          path: app/build/reports
          destination: reports/app
      - store_artifacts:
          path: build/reports
          destination: reports/project
      - store_test_results: # https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/outputs/androidTest-results/connected/debug/flavors/product/

  publish-github-release:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat ./app/build/version)
            ghr -t "${GITHUB_TOKEN}"  -u "${CIRCLE_PROJECT_USERNAME}" -r "${CIRCLE_PROJECT_REPONAME}" -c "${CIRCLE_SHA1}" "v${VERSION}" ./app/build/outputs/apk/product/release/app-product-release.apk
  publish-play-store:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - checkout
      - restore_cache:
          key: rbenv-{{ checksum "Gemfile.lock" }}-{{ checksum "Gemfile" }}-{{ checksum ".ruby-version" }}
      - run:
          name: Run setup script
          command: bin/setup
      - save_cache:
          paths:
            - ~/.rbenv
          key: rbenv-{{ checksum "Gemfile.lock" }}-{{ checksum "Gemfile" }}-{{ checksum ".ruby-version" }}
      - attach_workspace:
          at: .
      - run:
          name: Create google-play-service.json
          command: printf "%s" "${GOOGLE_PLAY_SERVICE_JSON}" | base64 --decode > google-play-service.json
      - run:
          name: "Publish to Google Play Store"
          command: |
            bin/fastlane supply \
            --track internal \
            --aab ./app/build/outputs/bundle/productRelease/app-product-release.aab \
            --release_status draft

workflows:
  version: 2
  all:
    jobs:
      - build
      - androidTest:
          requires:
            - build
          matrix:
            parameters:
              system_image:
                - android-36;google_apis;x86_64
                - android-26;google_apis;x86_64
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              only: release
      - publish-play-store:
          requires:
            - build
          filters:
            branches:
              only: release

