version: 2.1

executors:
  android_executor: &android_executor
    docker:
      - image: cimg/android:2025.08.1
    resource_class: large
    environment:
      JVM_OPTS: -Xmx3200m

commands:
  cache_gradle_dependencies:
    steps:
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "settings.gradle" }}-{{ checksum "dependencies.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "settings.gradle" }}-{{ checksum "dependencies.gradle" }}
  create_google_services_develop:
    steps:
      - run:
          name: Create google-services.json (develop flavour)
          command: |
            rm app/src/develop/google-services.json # symlink, for local builds
            printf "%s" "${GOOGLE_SERVICES_DEVELOP}" | base64 --decode > app/src/develop/google-services.json      

jobs:
  build:
    working_directory: ~/code
    <<: *android_executor
    environment:
      ORG_GRADLE_PROJECT_RELEASE_STORE_FILE: /home/circleci/code/release.keystore
      ORG_GRADLE_PROJECT_RELEASE_STORE_PASSWORD_FILE: /home/circleci/code/release.password
      ORG_GRADLE_PROJECT_RELEASE_KEY_PASSWORD_FILE: /home/circleci/code/release.password
    steps:
      - checkout
      - cache_gradle_dependencies
      - create_google_services_develop
      - run:
          name: Create google-services.json (product flavour)
          command: |
            rm app/src/product/google-services.json # symlink, for local builds
            printf "%s" "${GOOGLE_SERVICES}" | base64 --decode > app/src/product/google-services.json
      - run:
          name: Create release.password
          command: printf "%s\n" "${RELEASE_KEY_PASSWORD:-}" > "${ORG_GRADLE_PROJECT_RELEASE_KEY_PASSWORD_FILE}"
      - run:
          name: Create release.keystore
          command: printf "%s" "${RELEASE_KEYSTORE:-}" | base64 --decode > "${ORG_GRADLE_PROJECT_RELEASE_STORE_FILE}"
      - run:
          name: gradle check
          command: ./gradlew check
      - run:
          name: gradle assembleProduct
          command: ./gradlew assembleProduct
      - run:
          name: gradle bundleProductRelease
          command: ./gradlew bundleProductRelease
      - store_artifacts: # https://circleci.com/docs/2.0/artifacts/
          path: app/build/outputs/apk/product/release/app-product-release.apk
          destination: apks/app-product-release.apk
      - store_artifacts:
          path: app/build/outputs/bundle/productRelease/app-product-release.aab
          destination: aabs/app-product-release.aab
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results: # https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results
      - persist_to_workspace:
          root: app/build
          paths:
            - version
            - outputs
  publish-github-release:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: ./app/build
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat ./app/build/version)
            ghr -t "${GITHUB_TOKEN}"  -u "${CIRCLE_PROJECT_USERNAME}" -r "${CIRCLE_PROJECT_REPONAME}" -c "${CIRCLE_SHA1}" "v${VERSION}" ./app/build/outputs/apk/product/release/app-product-release.apk
  publish-play-store:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - checkout
      - restore_cache:
          key: rbenv-{{ checksum "Gemfile.lock" }}-{{ checksum "Gemfile" }}-{{ checksum ".ruby-version" }}
      - run:
          name: Run setup script
          command: bin/setup
      - save_cache:
          paths:
            - ~/.rbenv
          key: rbenv-{{ checksum "Gemfile.lock" }}-{{ checksum "Gemfile" }}-{{ checksum ".ruby-version" }}
      - attach_workspace:
          at: ./app/build
      - run:
          name: Create google-play-service.json
          command: printf "%s" "${GOOGLE_PLAY_SERVICE_JSON}" | base64 --decode > google-play-service.json
      - run:
          name: "Publish to Google Play Store"
          command: |
            bin/fastlane supply \
            --track internal \
            --aab ./app/build/outputs/bundle/productRelease/app-product-release.aab \
            --release_status draft

workflows:
  version: 2
  all:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              only: release
      - publish-play-store:
          requires:
            - build
          filters:
            branches:
              only: release

