plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'com.mikepenz.aboutlibraries.plugin'
    id 'kotlin-android'
    id 'com.google.devtools.ksp'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
    id 'io.gitlab.arturbosch.detekt'
}

apply from: '../dependencies.gradle'

static String getBranchName() {
    final branchCommand = ["git", "symbolic-ref", "HEAD", "--short"]
    return branchCommand.execute().text.trim()
}

static boolean isVersioned() {
    return getBranchName() == "release"
}

/**
 * The android "version code", from the highest-number changelog file.
 */
static int findVersionCode() {
    final int versionCode
    if (isVersioned()) {
        def versionNameScript = new File("bin/versionNumber")
        final stdout = [versionNameScript].execute().text.trim()
        versionCode = Integer.parseInt(stdout)
    } else {
        versionCode = 1
    }
    return versionCode
}

/**
 * The android "version name".
 */
static String findVersionName() {
    if (!isVersioned()) {
        return "0.0.1"
    }
    return "0.0.${findVersionCode()}"
}

def releaseStoreFile = file(RELEASE_STORE_FILE, PathValidation.NONE)

android {
    compileSdk=36
    defaultConfig {
        applicationId "uk.me.jeremygreen.merging2"
        minSdkVersion 21
        targetSdkVersion 36
        versionCode findVersionCode()
        versionName findVersionName()
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildFeatures {
        viewBinding = true
        buildConfig = true
        compose = true
    }
    signingConfigs {
        release {
            storeFile releaseStoreFile
            storePassword file(RELEASE_STORE_PASSWORD_FILE).getText('UTF-8').trim()
            keyPassword file(RELEASE_KEY_PASSWORD_FILE).getText('UTF-8').trim()
            keyAlias RELEASE_KEY_ALIAS
        }
    }
    buildTypes {
        release {
            if (releaseStoreFile.exists()) {
                signingConfig signingConfigs.release
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    flavorDimensions "flavour"
    productFlavors {
        develop {
            dimension "flavour"
            applicationId "uk.me.jeremygreen.merging2.develop"
        }
        product {
            dimension "flavour"
        }
    }
    namespace 'uk.me.jeremygreen.merging2'
}

detekt {
    buildUponDefaultConfig = true
    config.setFrom("../detekt.yml")
}

dependencies {
    def lifecycle_version = "2.9.3"
    def room_version = "2.7.2"
    def composeBom = platform('androidx.compose:compose-bom:2025.08.01')
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // JetPack Compose
    implementation composeBom
    implementation 'androidx.compose.material3:material3'
    implementation("androidx.compose.runtime:runtime-livedata:1.9.0")
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.activity:activity-compose'
    debugImplementation 'androidx.compose.ui:ui-tooling'
    debugImplementation 'androidx.compose.ui:ui-test-manifest'

    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2"
    implementation 'androidx.annotation:annotation:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:${lifecycle_version}"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:${lifecycle_version}"
    implementation "androidx.room:room-ktx:${room_version}"
    implementation "androidx.room:room-runtime:${room_version}"
    implementation("io.coil-kt:coil:2.7.0")
    implementation("io.coil-kt:coil-compose:2.7.0")
    implementation 'com.facebook.fresco:fresco:3.1.3'
    // https://github.com/facebook/fresco/issues/2598#issuecomment-1110860661
    compileOnly 'com.facebook.infer.annotation:infer-annotation:0.18.0'
    implementation platform('com.google.firebase:firebase-bom:29.0.4')
    implementation 'com.google.firebase:firebase-crashlytics' // versioned with BOM
    implementation 'com.google.firebase:firebase-analytics' // versioned with BOM
    implementation 'com.google.android.gms:play-services-mlkit-face-detection:16.1.4'
    implementation "com.mikepenz:aboutlibraries-compose-m3:${aboutLibsVersion}"
    ksp "androidx.room:room-compiler:${room_version}"
    testImplementation "androidx.arch.core:core-testing:2.1.0"
    testImplementation "androidx.room:room-testing:${room_version}"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    androidTestImplementation composeBom
    androidTestImplementation 'androidx.compose.ui:ui-test-junit4'
    detektPlugins("io.gitlab.arturbosch.detekt:detekt-rules-libraries:1.23.8")
    detektPlugins("io.gitlab.arturbosch.detekt:detekt-rules-ruleauthors:1.23.8")
    detektPlugins 'io.nlopez.compose.rules:detekt:0.4.27'
}

task writeVersionFile {
    doLast {
        def versionFile = file("${buildDir}/version")
        versionFile.parentFile.mkdirs()
        versionFile.write(findVersionName(), "UTF-8")
    }
}

preBuild.dependsOn(writeVersionFile)
